### ISSUE TITLE
Issue when trying to run build-package

### ISSUE THREAD

**Issue by tcveritas** [open-power-host-os/builds#168]
I'm running into an issue when trying to run the build-package command. This is after I created a user "admin" and su - to it 

![build-package](https://cloud.githubusercontent.com/assets/25467720/22485593/db4c2a4e-e7cb-11e6-9a64-a3a9de2b3ce7.PNG)

**Comment by tcveritas** [comment]
I was able to move past this issue thanks to the response in issue #166. However, I am now running into the following error. This is my first go-around using github, so any help would be appreciated 
![nexterror](https://cloud.githubusercontent.com/assets/25467720/22485931/14f9a220-e7cd-11e6-90c0-84a787807e05.PNG)

**Comment by gutoyr** [comment]
Seems that the user used to clone open-power-host-os/builds repository is not the same as the one that executed `python host_os.py build-package`.

When building the packages, host_os.py tries to write inside open-power-host-os/builds repository, therefore, the user that executes `python host_os.py build-package` must be the same as the one passed to `sudo python host_os.py set-env --user <my_user>`.

The easiest way to fix it is starting from the beginning, following this steps:

1. log as **user1**
2. as **user1**, clone open-power-host-os/builds repository
`git clone https://github.com/open-power-host-os/builds.git`
3. set build enviroment for **user1**
`sudo python set-env --user user1`
4. as **user1**, build the packages
`python build-package`

This information is missing in the project documentation, I will address it.

**Comment by tcveritas** [comment]
That helped me make progress, but it still failed out. Looks like it's failing on trying to find a RHEL repo? 
![issue3](https://cloud.githubusercontent.com/assets/25467720/22514625/8b93e79a-e865-11e6-9247-13d090874cdd.PNG)

**Comment by gutoyr** [comment]
svn failed to checkout gcc repository, probably due to some sort of network issue. You can try to do it manually before build the packages:

`svn checkout svn://gcc.gnu.org/svn/gcc/branches/redhat/gcc-4_8-branch /var/lib/host-os/repositories/gcc`

then:

`python host_os.py build-package`

If the _svn checkout_ fails, then it is a network issue. In this case, you can try what is suggested by gnu/gcc [1] under "Using the SVN repository" topic and  replace "svn://" with "http://".

[1] https://www.gnu.org/software/gcc/svn.html

**Comment by tcveritas** [comment]
Still seems to be throwing the same error after following the process above 
![error2_8](https://cloud.githubusercontent.com/assets/25467720/22757069/04606046-ee0f-11e6-9e0d-1ae4f8fb8beb.PNG)

**Comment by gutoyr** [comment]
It is due to the user, who is running `host_os.py`, does not have _write permission_ in the current directory. It can be double checked by running `touch test_file` command in the repository directory, in case it fails the user is lacking the _write permission_.

It is recommended to run `host_os.py` with the same user used to clone builds git repository in order to avoid coming across permission access issues.

**Comment by alanoe** [comment]
Why would someone need to clone the builds git repository with a user and try to run host_os.py with another?

**Comment by olavphibm** [comment]
@alanoe Our README mentions that the script accepts a new user as an argument, which it will then create. This new user will not have permissions to access/modify the previously cloned builds repository. Maybe that's a use case we should not support at all.

**Comment by tcveritas** [comment]
Thanks for the replies. 

I think the issue that I am hitting now (after changing the permissions to writable by my user) is the fact that my system cannot pull in the code from gcc.gnu.org using the svn method. gutoyr commented on this 2 weeks ago in this thread. I am able to pull it in using http://

However, I've gone through and manually changed the code to reflect this within the following two files:
/builds/versions/gcc/CentOS/7/gcc.spec
/builds/versions/gcc/gcc.yaml

When running the build-package script, it seems to flip these back to svn and fails out. Any idea how to permanently change this?

**Comment by olavphibm** [comment]
@tcveritas 
The builds script checks out a commit of the versions repository and resets the files to this specific commit. The recommended way to change the URL of a package is to create a commit with the modifications, push it to your private repository and pass this repository URL to the `--build-versions-repository-url` parameter, along with the branch/commit ID to the `--build-version` parameter. For example:
`python host_os.py build-package --build-versions-repository-url https://github.com/olavphibm/versions.git --build-version dev`

A faster way to do it is to modify the repository cloned at `versions/` directory, commit and pass the commit ID to the command, for example:
`python host_os.py build-package --build-version adc29783cae1d8125c0a5c0fabb68148343b3f56`

Please note that the `versions/` directory might have a path change in the future, which could cause any changes made to the local repository (second option) to be "lost".

We'll soon work on a way to make this URL modifications easier, by allowing them to be passed through command line.

**Comment by tcveritas** [comment]
I am now hitting this error when trying to run host_os.py build-package 

Should I be seeing this many errors?
![image](https://cloud.githubusercontent.com/assets/25467720/23266495/8f39fa34-f9ad-11e6-8107-9536cd7ebe22.png)

**Comment by alanoe** [comment]
TC> I am now hitting this error when trying to run host_os.py build-packageUse "python host_os.py build-package" instead.

host_os.py became executable in a patch merged one week ago, so alternatively you could pull latest changes to your cloned builds git repository

**Comment by mopsfelder** [comment]
@tcveritas The https://github.com/open-power-host-os/builds/pull/191 fix has been merged and the procedure to setup environment changed slightly.

Can you try from scratch again and see if there is any issue left to be addressed?

**Comment by fabianorosas** [comment]
The code changed a lot since #191 was merged. Please open a [new issue](https://github.com/open-power-host-os/builds/issues/new) if you have further problems.
