### ISSUE TITLE
README suggests possibly sub-optimal steps (e.g., SMT off for builds too, instead of only to run KVM guests)

### ISSUE THREAD

**Issue by mfoliveira** [open-power-host-os/builds#186]
Currently, the README.rst file (landing page for this project [1]) suggests to set SMT off in the general case (e.g., build and run).

> Settings
> Disable SMT
> $ sudo ppc64_cpu --smt=off

Indeed, SMT off is required to run KVM guests. 
However, that's not a technical limitation when building the packages, and actually SMT on would help with the build speed if multiple make jobs are being used (i.e., `make -jN`).

So, it would be great to take advantage of more threads (if the package build scripts/SPECs don't already do it), and clarify the scenarios that (don't ) need SMT off.

[1] https://github.com/open-power-host-os/builds/

**Comment by fabianorosas** [comment]
Yes, the documentation certainly needs to be made more clear in that aspect. Thank you for taking the time to report this.

For completeness, here's a complementary discussion: https://github.com/open-power-host-os/builds/issues/16

**Comment by mfoliveira** [comment]
@fabianorosas okay, thank you.

**Comment by mfoliveira** [comment]
@fabianorosas noticed something else in README that I believe we could improve in the benefit of our users / user experience; so I just changed this issue's title to be more general (rather than open a new one for a minor thing. Let me know if you'd prefer it otherwise).

Any reason why the installation of `epel-release` is split into 2 commands?

```
$ sudo yum install --downloadonly --downloaddir=. epel-release
$ sudo yum localinstall epel-release-7-5.noarch.rpm # Note the version may change.
```

It's possible to install it with:
```
$ sudo yum install epel-release
```

It has the advantage of being version independent, thus not requiring to have users to read/care about a caveat note on the version number.
Which, by the way, happened to change version numbers to 7-6, so the single-command variant would help with that  :)

```
# rpm  -q epel-release
epel-release-7-6.noarch
```

**Comment by mfoliveira** [comment]
This would be much better in usability/ux terms in the form a meta-package; e.g., `host-os-build-deps`

```
$ sudo yum install -y $(cat rpm_requirements.txt)
```

**Comment by mfoliveira** [comment]
And this too, but totally agree with the point here:

> We decided that's is a little bit intrusive to install all the produced RPMs since some of them may not fit your needs. [snip]

However, again in the benefit of our users, I'd suggest to make _multiple_ meta-packages at different levels of dependencies installed.
That's because, even though some users _value_ the respect we've had for them with that decision, they would _also value_ having an easier method of just getting _some_ things installed in an easier way.

For example,
```
host-os-pkgs-basic or -virt # e.g., kernel, qemu/slof, libvirt 
host-os-pkgs-ras # e.g., ppc64-diag, servicelog
```

I see there's apparently something already aligned with that in the `config.yaml` file, using package groups.

Is that available to the users?

Thanks!

**Comment by mfoliveira** [comment]
It would be nice too to include `git clone` instructions for the builds repo, so users can follow the steps along without having to stop and, 'hey, now let me get back to the top of the page to get the clone link, stop this, clone that, and get back / scroll back here' :-)

```
git clone https://github.com/open-power-host-os/builds.git
cd builds
```

**Comment by mfoliveira** [comment]
This paragraph should _clarify_ that the user is created if it doesn't exist already.
It's a bit unclear here (e.g., it seems it will work even if the user doesn't exist, but not sure if you have to create it or not)

```
$ sudo python host_os.py set-env --user LOGIN
Naturally, you need to replace LOGIN by the user name you'll use to run host_os.py, which should not run using root user, even if that user doesn't exist yet.
```

I got an error on `useradd` right away, which would have been skipped if I had read that sort of wording :)

```
# useradd -m -s /bin/bash hostos-builder
useradd: user 'hostos-builder' already exists
```

**Comment by mfoliveira** [comment]
Oops, and by the way, that automatic `useradd` probably needs to be fixed to use the `--create-home` argument.

Just hit this trying to login after running `host_os.py set-env` and having it create the user for me.

 ```
user@system's password:
Could not chdir to home directory /home/hostos-builder: No such file or directory
```

**Comment by mfoliveira** [comment]
And any reason why `host_os.py` has no `execute` bit set, so we can run it as `./host_os.py` ?

It's running OK as executable after I change it, thus no longer `python host_os.py <args>`:

```
$ sed "1i #!$(which python)" -i host_os.py 
$ chmod +x host_os.py 

$ ./host_os.py --help
```

Thanks!

**Comment by fabianorosas** [comment]
> This would be much better in usability/ux terms in the form a meta-package; e.g., host-os-build-deps or package group.

Discussing this with the team, we have reached the conclusion that this is not feasible at this point, because there is no way to provide the package to the user without having a dedicated Open POWER Host OS external repository. The user would have to build this package along with other Host OS packages and would therefore need the dependencies already installed.

Alternatively, having a script that installs the dependencies is about the same as having a `yum install <(cat rpm_requirements)` like we have today as that would still require copy/paste of a line from the readme file.

Does anyone see a way around this? Otherwise I think we are going to have to reject this particular issue.

**Comment by mfoliveira** [comment]
Hi @fabianorosas 

Thanks for considering/discussing it.
I see it's a chicken-and-egg problem given the restriction of not having a binary package repository (and how _binary_ RPM is; i.e., compare w/ DEB packages which are more human-readable/plain-text based).

Given that telling the user to build and RPM to install build deps is much worse, I believe it's better to reject it for now, per that binary distribution restriction in place.

Please note there are further documentation change suggestions in this issue, which hopefully you/team may find useful.

Thank you.

**Comment by mfoliveira** [comment]
Hello guys,

It's awesome to see how quickly you've been implementing or staging some of the suggested changes.
Thank you for your consideration. Hope this helps the community adoption and user experience to be as straightforward and intuitive as possible.

I've recently noticed a couple of other things:

1) `$ sudo yum install -y $(cat rpm_requirements.txt)` is done before `git clone` of the `builds` repo, so the file is not yet local. I'd suggest to either replace it with a github http URL, or putting this step /after/ the `git clone` step, so the file actually exists.

2) The `readme.rst` 's steps show `host_os.py build-package` which fails, as it's missing a trailing `s` (for `build-packages`).

**Comment by olavphibm** [comment]
@mfoliveira, thanks for pointing it out, those two issues are being addressed in https://github.com/open-power-host-os/builds/pull/215

**Comment by olavphibm** [comment]
The documentation regarding SMT has been updated in https://github.com/open-power-host-os/builds/pull/233 and we now have the `open-power-host-os-release` package, which disables SMT in the system where it is installed to prepare for virtualization.

I believe the other issues have been taken care of and are all referenced here.
