### ISSUE TITLE
Fedorahosted Retired

### ISSUE THREAD

**Issue by zipsterific** [open-power-host-os/builds#205]
So I was building away for a couple hours and hit this snag last night. 

GitCommandError: 'git clone -v https://git.fedorahosted.org/git/hwdata.git workspace/repositories/hwdata' returned with exit code 128
stderr: 'fatal: https://git.fedorahosted.org/git/hwdata.git/info/refs not valid: is this a git repository?

The sad news from fedorahosted.org....
"fedorahosted.org was retired on March 1st, 2017."

**Comment by olavphibm** [comment]
Hi, that hit us by surprise too.
We'll contact the hwdata maintainers to find out where its repository will be moved to, but, as a workaround, we're keeping the archived repository snapshot in our versions repository,
A fix has been issued (https://github.com/open-power-host-os/versions/pull/140), so you should be able to update your repos and build from master right now.

**Comment by zipsterific** [comment]
Appreciate it! 
//Al
