### ISSUE TITLE
Don't run the build as root

### ISSUE THREAD

**Issue by mpe** [open-power-host-os/builds#21]
The documentation suggests that the build should be run as root, but that is poor practice:

```
# sudo python host-os-build.py --verbose
```

The docs should be updated to omit the `sudo`, instead only requiring `sudo` for tasks that must be run as root, such as installing packages.

**Comment by maurorodrigues** [comment]
Thanks @mpe! I agree with you and It is already on my top priority list. I'll push a fix soon
