### ISSUE TITLE
Dependancy issue while installing qemu on power9

### ISSUE THREAD

**Issue by sathnaga** [open-power-host-os/builds#232]
--> Finished Dependency Resolution
Error: Package: 15:qemu-system-ppc-2.8.0-7.git2c99cbf.el7.centos.ppc64le (hostos)
           Requires: librbd.so.1()(64bit)
Error: Package: 15:qemu-img-2.8.0-7.git2c99cbf.el7.centos.ppc64le (hostos)
           Requires: librbd.so.1()(64bit)
Error: Package: 15:qemu-system-ppc-2.8.0-7.git2c99cbf.el7.centos.ppc64le (hostos)
           Requires: librados.so.2()(64bit)
Error: Package: 15:qemu-img-2.8.0-7.git2c99cbf.el7.centos.ppc64le (hostos)
           Requires: librados.so.2()(64bit)
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest

**Comment by sathnaga** [comment]
adding epel,repo helped solving this

**Comment by fabianorosas** [comment]
Yes, this issue is caused by missing the EPEL repository. For anyone bumping into this in the future:

```
sudo yum install epel-release
```
