### ISSUE TITLE
Need specific instructions on how to build a bootable ISO on HostOS / PPC

### ISSUE THREAD

**Issue by th48ad** [open-power-host-os/builds#235]
In order to run our VM on HostOS we need to boot it from an ISO.

**Comment by rmatinata-ibm** [comment]
[boot-iso.tar.gz](https://github.com/open-power-host-os/builds/files/883776/boot-iso.tar.gz)

0. go to a CentOS 7.x
1. Take the attached tarball and extract somewhere. Make sure you are cwd to its contents.
2. copy your initrd.img and vmlinuz to ppc/ppc64 and tweak ./boot/grub/grub.cfg as needed. If you need it, add a roots wherever (as long as grub.cfg reflects this)
3. run the following command:
`grub2-mkimage --format=powerpc-ieee1275 --directory=/usr/lib/grub/powerpc-ieee1275 --prefix="()/"boot/grub --output=./boot/grub/powerpc-ieee1275/core.elf`
4. copy over /usr/lib/grub/powerpc-ieee1275/*.mod to ./boot/grub/powerpc-ieee1275
5. copy over /usr/lib/grub/powerpc-ieee1275/*.lst ./boot/grub/powerpc-ieee1275
6. Create the ISO:
`mkisofs -v -r -T -U -l -cache-inodes -chrp-boot -V "vol_id" -o ../boot.iso  ./`
tweak vol_id and boot.iso strings to suite your case

**Comment by rmatinata-ibm** [comment]
@cuinutanix and @th48ad please let us know if it worked for you...

**Comment by olavphibm** [comment]
@th48ad These instructions might be useful to you: https://github.com/open-power-host-os/builds/blob/master/BUILDING_AN_ISO.md
If you wish a minimal ISO with only virtualization packages, for example, you could remove the groups from `iso_repo_packages_groups` in `config.yaml`, leaving only `"OpenPOWER Host OS virtualization"`
