### ISSUE TITLE
Unable to bring up Network with NIC configured with bnx2x driver

### ISSUE THREAD

**Issue by santwana** [open-power-host-os/builds#25]
After updating to HostOS 1.0(k.v- 4.7.0-1.el7.centos.pkvm3_1_1.3100.0.ppc64le) from CentOS-7.2(3.10.0-327.el7.ppc64le ), the NIC doesn't come up. 

The same issue wasn't noticed on the CentOS base kernel. Issue surfaces only after HostOS layer installation. So this bug.

The NIC is Shiner-SR adapter, which is bnx2x driver.
#ethtool -i net0
driver: bnx2x
version: 1.712.30-0
firmware-version: bc 7.10.4
bus-info: 0001:0c:00.2
supports-statistics: yes
supports-test: yes
supports-eeprom-access: yes
supports-register-dump: yes
supports-priv-flags: yes

Trying to bring up the NIC manually , gives the below error:
#ifconfig net0 up
[ 226.594896] bnx2x 0001:0c:00.2: Direct firmware load for bnx2x/bnx2x-e2-7.13.1.0.fw failed with error -2
[ 226.595182] bnx2x: [bnx2x_init_firmware:13444(net0)]Can't load firmware file bnx2x/bnx2x-e2-7.13.1.0.fw
[ 226.595321] bnx2x: [bnx2x_func_hw_init:5785(net0)]Error loading firmware
[ 226.595377] bnx2x: [bnx2x_nic_load:2727(net0)]HW init failed, aborting
SIOCSIFFLAGS: No such file or directory

Snip from the Host dmesg, as below:
[ 16.263532] bnx2x: QLogic 5771x/578xx 10/20-Gigabit Ethernet Driver bnx2x 1.712.30-0 (2014/02/10)
[ 16.263670] bnx2x 0001:0c:00.0: msix capability found
[ 16.288163] bnx2x 0001:0c:00.0: Using 64-bit DMA iommu bypass
[ 16.288318] bnx2x 0001:0c:00.0: part number 0-0-0-0
[ 16.374473] bnx2x 0001:0c:00.1: msix capability found
[ 16.387891] bnx2x 0001:0c:00.1: Using 64-bit DMA iommu bypass
[ 16.387929] bnx2x 0001:0c:00.1: part number 0-0-0-0
[ 16.449931] bnx2x 0001:0c:00.2: msix capability found
[ 16.467894] bnx2x 0001:0c:00.2: Using 64-bit DMA iommu bypass
[ 16.467933] bnx2x 0001:0c:00.2: part number 0-0-0-0
[ 16.530389] bnx2x 0001:0c:00.3: msix capability found
[ 16.547883] bnx2x 0001:0c:00.3: Using 64-bit DMA iommu bypass
[ 16.547918] bnx2x 0001:0c:00.3: part number 0-0-0-0
[ 16.611717] bnx2x 0001:0c:00.0 enP1p12s0f0: renamed from eth0
[ 17.187959] bnx2x 0001:0c:00.1 enP1p12s0f1: renamed from eth1
[ 17.497939] bnx2x 0001:0c:00.2 enP1p12s0f2: renamed from eth2
[ 17.837940] bnx2x 0001:0c:00.3 enP1p12s0f3: renamed from eth4
[ 34.247494] bnx2x 0001:0c:00.2 net0: renamed from enP1p12s0f2
[ 57.569413] bnx2x 0001:0c:00.0: Direct firmware load for bnx2x/bnx2x-e2-7.13.1.0.fw failed with error -2
[ 58.542474] bnx2x: [bnx2x_init_firmware:13444(enP1p12s0f0)]Can't load firmware file bnx2x/bnx2x-e2-7.13.1.0.fw
[ 58.571110] bnx2x: [bnx2x_func_hw_init:5785(enP1p12s0f0)]Error loading firmware
[ 58.937230] bnx2x: [bnx2x_nic_load:2727(enP1p12s0f0)]HW init failed, aborting
[ 59.657842] bnx2x 0001:0c:00.2: Direct firmware load for bnx2x/bnx2x-e2-7.13.1.0.fw failed with error -2
[ 60.047987] bnx2x: [bnx2x_init_firmware:13444(net0)]Can't load firmware file bnx2x/bnx2x-e2-7.13.1.0.fw
[ 60.055021] bnx2x: [bnx2x_func_hw_init:5785(net0)]Error loading firmware
[ 60.295266] bnx2x: [bnx2x_nic_load:2727(net0)]HW init failed, aborting
[ 61.597857] bnx2x 0001:0c:00.1: Direct firmware load for bnx2x/bnx2x-e2-7.13.1.0.fw failed with error -2
[ 62.068550] bnx2x: [bnx2x_init_firmware:13444(enP1p12s0f1)]Can't load firmware file bnx2x/bnx2x-e2-7.13.1.0.fw
[ 62.068552] bnx2x: [bnx2x_func_hw_init:5785(enP1p12s0f1)]Error loading firmware
[ 62.068557] bnx2x: [bnx2x_nic_load:2727(enP1p12s0f1)]HW init failed, aborting
[ 62.297854] bnx2x 0001:0c:00.3: Direct firmware load for bnx2x/bnx2x-e2-7.13.1.0.fw failed with error -2
[ 62.297857] bnx2x: [bnx2x_init_firmware:13444(enP1p12s0f3)]Can't load firmware file bnx2x/bnx2x-e2-7.13.1.0.fw
[ 62.297859] bnx2x: [bnx2x_func_hw_init:5785(enP1p12s0f3)]Error loading firmware
[ 62.297864] bnx2x: [bnx2x_nic_load:2727(enP1p12s0f3)]HW init failed, aborting

**Comment by bssrikanth** [comment]
This issue is affecting other machines as well where we have only Shiner-SR as primary adapter connecting to the lab network. Please resolve the issue asap

**Comment by maurorodrigues** [comment]
Hi @santwana thank you for the report. I will add linux-firmware package in the build process, it will be available on the next wednesday build.

**Comment by bssrikanth** [comment]
@maurorodrigues please provide the package location.

**Comment by maurorodrigues** [comment]
@bssrikanth the linux-firmware package is available on the very same repository you used to install the last week build (I'm not sure I can post the url externally), please try:
```
# sudo yum remove ivtv-firmware # it conflicts w/ the new package
# sudo yum update linux-firmware```

It will install linux-firmware-20150904-44.git70a3c2a.el7.centos.1.noarch.rpm which contains bnx2x/bnx2x-e2-7.13.1.0.fw, Hopefully this solves the issue, if so please close the bug, if it doesn't please let me know and I'll get in touch to, if possible, access the test system for further investigation.

**Comment by santwana** [comment]
After updating the "linux-firmware" to linux-firmware-20150904-44.git70a3c2a.el7.centos.1.noarch, the issue is solved now.
The NIC configured with bnx2x driver, is accessible.
Thanks @maurorodrigues , will close this issue now.
