### ISSUE TITLE
HostOS repo: package dependency for installation of libvirt and qemu

### ISSUE THREAD

**Issue by balamuruhans** [open-power-host-os/builds#26]
---Problem Description---
Couldn't install libvirt and qemu after installation of CentOS and updating with HostOS repo due to package dependency.
Below packages are not available in HostOS repo,
    - 1:librados2-0.80.7-0.8.el7.ppc64le 
    - 1:librbd1-0.80.7-0.8.el7.ppc64le

---uname output---
#uname -a
Linux 4.7.0-1.el7.centos.pkvm3_1_1.3100.0.ppc64le #1 SMP Wed Aug 17 13:38:15 CDT 2016 ppc64le ppc64le ppc64le GNU/Linux

---Steps to Reproduce---
1. Install CentOS and yum update with HostOS repo.
2. Reboot the machine and tried to install libvirt and qemu
#sudo yum install libvirt qemu
3. Below issue is observed, where packages are taken from epel repo and not from hostos repo

Packages skipped because of dependency problems:
1:librados2-0.80.7-0.8.el7.ppc64le from epel
1:librbd1-0.80.7-0.8.el7.ppc64le from epel
libseccomp-2.3.1-0.el7.centos.1.ppc64le from hostos
libvirt-1.3.4-1.el7.centos.pkvm3_1_1.3100.0.ppc64le from hostos
libvirt-daemon-config-network-1.3.4-1.el7.centos.pkvm3_1_1.3100.0.ppc64le from hostos
libvirt-daemon-config-nwfilter-1.3.4-1.el7.centos.pkvm3_1_1.3100.0.ppc64le from hostos
libvirt-daemon-driver-interface-1.3.4-1.el7.centos.pkvm3_1_1.3100.0.ppc64le from hostos
libvirt-daemon-driver-lxc-1.3.4-1.el7.centos.pkvm3_1_1.3100.0.ppc64le from hostos
libvirt-daemon-driver-nodedev-1.3.4-1.el7.centos.pkvm3_1_1.3100.0.ppc64le from hostos
libvirt-daemon-driver-nwfilter-1.3.4-1.el7.centos.pkvm3_1_1.3100.0.ppc64le from hostos
libvirt-daemon-driver-qemu-1.3.4-1.el7.centos.pkvm3_1_1.3100.0.ppc64le from hostos
libvirt-daemon-driver-secret-1.3.4-1.el7.centos.pkvm3_1_1.3100.0.ppc64le from hostos
libvirt-daemon-driver-storage-1.3.4-1.el7.centos.pkvm3_1_1.3100.0.ppc64le from hostos
libvirt-daemon-kvm-1.3.4-1.el7.centos.pkvm3_1_1.3100.0.ppc64le from hostos
libvirt-daemon-lxc-1.3.4-1.el7.centos.pkvm3_1_1.3100.0.ppc64le from hostos
libvirt-daemon-qemu-1.3.4-1.el7.centos.pkvm3_1_1.3100.0.ppc64le from hostos
11:qemu-2.6.93-6.el7.centos.pkvm3_1_1.3100.0.ppc64le from hostos
11:qemu-common-2.6.93-6.el7.centos.pkvm3_1_1.3100.0.ppc64le from hostos
11:qemu-img-2.6.93-6.el7.centos.pkvm3_1_1.3100.0.ppc64le from hostos
11:qemu-kvm-2.6.93-6.el7.centos.pkvm3_1_1.3100.0.ppc64le from hostos
11:qemu-system-ppc-2.6.93-6.el7.centos.pkvm3_1_1.3100.0.ppc64le from hostos
11:qemu-system-x86-2.6.93-6.el7.centos.pkvm3_1_1.3100.0.ppc64le from hostos 

4. Currently we are proceeding our test by installation of libvirt and qemu with epel repo, but
dependencies are expected to be available in hostos repo

**Comment by maurorodrigues** [comment]
I chatted with @rmatinata-ibm earlier today and he agreed that we can use epel's package just fine. We can start building ceph package family in the future if any we need any additional patch on top of it though (and for such tests feedback are very welcome).

I will push a documentation change for the installation steps to close/fix this issue as a documentation issue.

**Comment by maurorodrigues** [comment]
Documented at https://github.com/open-power-host-os/builds/blob/master/README.rst#rpm-based-distributions
