### ISSUE TITLE
Update libvirt spec file

### ISSUE THREAD

**Issue by sgarfinkle** [open-power-host-os/builds#285]
Libvirt has been rebased to v3.6.0. Please update the spec file in the builds. Thanks!

<cde:info> Mirrored with LTC bug #157489 </cde:info>

**Comment by olavph** [comment]
Fixed by https://github.com/open-power-host-os/versions/pull/202

**Comment by cdeadmin** [comment]
------- Comment From olavph@br.ibm.com 2017-08-15 08:01:36 EDT-------
libvirt has been updated to version 3.6.0 in Host OS: https://github.com/open-power-host-os/versions/pull/202
