### ISSUE TITLE
hostos needs latest opal-prd package to work seemless with latest FW

### ISSUE THREAD

**Issue by sathnaga** [open-power-host-os/builds#306]
<cde:info> Mirrored with LTC bug https://bugzilla.linux.ibm.com/show_bug.cgi?id=165254 </cde:info>

hostos needs latest opal-prd package to work seemless with latest FW,
Recommendation from Opal team.

Currently it comes from el7

```
yum info opal-prd
Loaded plugins: fastestmirror, product-id, search-disabled-repos, subscription-manager
This system is not registered with an entitlement server. You can use subscription-manager to register.
Loading mirror speeds from cached hostfile
 * epel: epel.mirror.constant.com
Installed Packages
Name        : opal-prd
Arch        : ppc64le
Version     : 5.5.0
Release     : 1.el7
Size        : 149 k
Repo        : installed
From repo   : anaconda
Summary     : OPAL Processor Recovery Diagnostics Daemon
URL         : http://github.com/open-power/skiboot
License     : ASL 2.0
Description : This package provides a daemon to load and run the OpenPower firmware's
            : Processor Recovery Diagnostics binary. This is responsible for run time
            : maintenance of OpenPower Systems hardware.
```

**Comment by hegdevasant** [comment]
Please grab v5.10 from git and rebuild it.. Should be straight forward to build this package. (You may have to install powerpc64 cross compiler unless you have proper build environment like mock).

It creates opal-prd, opal-firmware and opal-utils package. You can pick up all 3 package.

[1] http://github.com/open-power/skiboot 

-Vasant

**Comment by mopsfelder** [comment]
I've sent a patch to update skiboot.spec to be able to package skiboot v5.10 release:

http://patchwork.ozlabs.org/patch/879888/

@fabianorosas is working on adding opal-prd and its sub-packages to HostOS.
