### ISSUE TITLE
latest hostos-devel: error while installing boot loader

### ISSUE THREAD

**Issue by bssrikanth** [open-power-host-os/builds#314]
<cde:info> Mirrored with LTC bug https://bugzilla.linux.ibm.com/show_bug.cgi?id=168728 </cde:info>

Observed an error during latest hostos-devel branch installation while Installing boot loader.. even though I can boot to installed centos -devel kernel entry from petitboot I cannot login to the host using the creds which I had configured during the installation. 

Error logs taken from installer : 

10:41:41,225 INFO anaconda: Creating prepboot on /dev/sdb1
10:41:41,565 INFO anaconda: Created prepboot on /dev/sdb1
10:41:42,310 INFO anaconda: Running pre-installation scripts
10:41:42,310 INFO anaconda: Running pre-installation scripts
10:52:49,180 INFO anaconda: Installing boot loader
10:52:49,181 INFO anaconda: boot loader stage1 target device is sdb1

10:52:49,181 INFO anaconda: boot loader stage2 target device is sdb2
LoaderImage object at 0x7fffb532bb10>ult image: <pyanaconda.bootloader.LinuxBoott

/sdb1:49,498 DEBUG anaconda: updateNVRAMBootList: self.stage1_device.path = /devv

-boston114/root rd.lvm.lv=host_os_ltc-boston114/swap console=hvc0.lv=host_os_ltcc

10:52:51,505 DEBUG anaconda: running handleException
10:52:51,507 CRIT anaconda: Traceback (most recent call last):

runile "/usr/lib64/python2.7/site-packages/pyanaconda/threads.py", line 227, in  

    threading.Thread.run(self, *args, **kwargs)

  File "/usr/lib64/python2.7/threading.py", line 765, in run
    self.__target(*self.__args, **self.__kwargs)

doInstallusr/lib64/python2.7/site-packages/pyanaconda/install.py", line 266, in  

    writeBootLoader(storage, payload, instClass, ksdata)

 in writeBootLoaderpython2.7/site-packages/pyanaconda/bootloader.py", line 2461,,

    writeBootLoaderFinal(storage, payload, instClass, ksdata)

 in writeBootLoaderFinaln2.7/site-packages/pyanaconda/bootloader.py", line 2389,,

    storage.bootloader.write()

 in writeusr/lib64/python2.7/site-packages/pyanaconda/bootloader.py", line 1610,,

    self.install()

 in installr/lib64/python2.7/site-packages/pyanaconda/bootloader.py", line 2039,,

    self.updateNVRAMBootList()

 in updateNVRAMBootListon2.7/site-packages/pyanaconda/bootloader.py", line 2052,,

    ["--print-config=boot-device"])

ecWithCapturelib64/python2.7/site-packages/pyanaconda/iutil.py", line 358, in exx

    filter_stderr=filter_stderr)[1]

un_programsr/lib64/python2.7/site-packages/pyanaconda/iutil.py", line 272, in _rr

    env_prune=env_prune)

artProgramsr/lib64/python2.7/site-packages/pyanaconda/iutil.py", line 196, in stt

    preexec_fn=preexec, cwd=root, env=env, **kwargs)

  File "/usr/lib64/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)

  File "/usr/lib64/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception

OSError: [Errno 2] No such file or directory

10:52:52,358 DEBUG anaconda: Gtk cannot be initialized

10:52:52,358 INFO anaconda: Thread Done: AnaInstallThread (140736114323888)
10:52:52,506 DEBUG anaconda: running handleException
10:52:52,507 CRIT anaconda: Traceback (most recent call last):

runile "/usr/lib64/python2.7/site-packages/pyanaconda/threads.py", line 227, in  

    threading.Thread.run(self, *args, **kwargs)

  File "/usr/lib64/python2.7/threading.py", line 765, in run
    self.__target(*self.__args, **self.__kwargs)

doInstallusr/lib64/python2.7/site-packages/pyanaconda/install.py", line 266, in  

    writeBootLoader(storage, payload, instClass, ksdata)

 in writeBootLoaderpython2.7/site-packages/pyanaconda/bootloader.py", line 2461,,

    writeBootLoaderFinal(storage, payload, instClass, ksdata)

 in writeBootLoaderFinaln2.7/site-packages/pyanaconda/bootloader.py", line 2389,,

 in writeusr/lib64/python2.7/site-packages/pyanaconda/bootloader.py", line 1610,,

    self.install()

 in installr/lib64/python2.7/site-packages/pyanaconda/bootloader.py", line 2039,,

    self.updateNVRAMBootList()

 in updateNVRAMBootListon2.7/site-packages/pyanaconda/bootloader.py", line 2052,,

    ["--print-config=boot-device"])

ecWithCapturelib64/python2.7/site-packages/pyanaconda/iutil.py", line 358, in exx

    filter_stderr=filter_stderr)[1]

un_programsr/lib64/python2.7/site-packages/pyanaconda/iutil.py", line 272, in _rr

    env_prune=env_prune)

artProgramsr/lib64/python2.7/site-packages/pyanaconda/iutil.py", line 196, in stt
    preexec_fn=preexec, cwd=root, env=env, **kwargs)

  File "/usr/lib64/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)

  File "/usr/lib64/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception

OSError: [Errno 2] No such file or directory

10:52:52,508 DEBUG anaconda: Gtk cannot be initialized
10:52:52,508 DEBUG anaconda: In the main thread, running exception handler
10:52:54,289 INFO anaconda: Running kickstart %%onerror script(s)
10:52:54,289 INFO anaconda: All kickstart %%onerror script(s) have been run
10:52:54,289 INFO anaconda: Running kickstart %%traceback script(s)
10:52:54,290 INFO anaconda: All kickstart %%traceback script(s) have been run
10:52:54,292 INFO anaconda: Running Thread: AnaInputThread22 (140736114323888)

**Comment by bssrikanth** [comment]
I have recreated this issue twice.

**Comment by bssrikanth** [comment]
This issue is hit as well with latest todays devel build. Any updates here?

**Comment by fabianorosas** [comment]
I see that the 'nvram' command is present in the latest build, so the issue should be fixed:

root@localhost:~/tmp $ chroot tmp4
root@localhost:/ $ which nvram
/usr/sbin/nvram

Could you confirm that you have the build from 2018-06-12 or a later one?
