### ISSUE TITLE
noVNC patches to implement QEMU RFB extension

### ISSUE THREAD

**Issue by danielhb** [open-power-host-os/builds#33]
Hi there,

Current noVNC master has a QEMU extension that I've implemented that allows for proper handling of international keyboards. I've backported this code to the 0.5.1 noVNC version in these 2 patches. You can find them in the attached ZIP file.

Thanks,

Daniel 

[novnc_qemu_extension.zip](https://github.com/open-power-host-os/builds/files/443203/novnc_qemu_extension.zip)

**Comment by maurorodrigues** [comment]
Thanks for bringing this up @danielhb.
I'll add noVNC as dependency to be built as soon as I add kimchi/ginger/gingerbase/wok to the build process. Hopefully I'll get this done before the next build, next wednesday.
