### ISSUE TITLE
Refactor code that deals w/ dependency

### ISSUE THREAD

**Issue by maurorodrigues** [open-power-host-os/builds#36]
There are 3 (maybe more?) types of dependencies:
- rpms (from external sources/distros ~~like f24's golang bootstrap golang/docker in centOS~~)
- version control systems (git, svn, cvs and so on)
  - which by itself breaks into multiple subclasses.
- external files (for instance jar files or when we're not able to generate them at build time - which in fact means that we need to specialize tar file preparations/setup steps).

Let's make classes specialized to deal with every situation.

**Comment by snowcrshd** [comment]
@maurorodrigues could you elaborate a bit more on the jar files (external files dependencies)?

I'm not sure what you mean regarding this and tar file setup.

**Comment by maurorodrigues** [comment]
@snowcrshd disregard the jar files itself, I was refering to http://download.savannah.nongnu.org/releases/fastjar/fastjar-0.97.tar.gz in gcc.yaml ... the jar in the sticked to my mind... 
anyway, external files,  like in gcc.yaml:
```
      - 'ftp://gcc.gnu.org/pub/gcc/infrastructure/isl-0.11.1.tar.bz2'
      - 'ftp://gcc.gnu.org/pub/gcc/infrastructure/cloog-0.18.0.tar.gz'
      - 'http://download.savannah.nongnu.org/releases/fastjar/fastjar-0.97.tar.gz'
```
The thing is external files are any files that aren't patch that we could keep on our SOURCES, or like those files under `download_build_files` section in the yamls, which usually refer to some Source[0-9]*in the spec file which in not track via git.
Note that docker, and soon kubernetes, have such  `download_build_files` due to our current inability to download multiple source codes at once.

**Comment by snowcrshd** [comment]
PR #128 closes this issue.
