### ISSUE TITLE
Make repository cloning parallel

### ISSUE THREAD

**Issue by maurorodrigues** [open-power-host-os/builds#4]
Even though, in the perfect world, it's only cloned once, repository cloning takes a long time. Let's at least make it parallel, if possible let's also look at pygit2 to make it faster or replace it if some other module do a better job on this task.

**Comment by maurorodrigues** [comment]
git clone --shallow might help to speed up things here as well

**Comment by mopsfelder** [comment]
We have switched to GitPython (which saved a reasonable amount of time during clone) and also put in place a cache mechanism for the downloaded repositories. There is no imediate need to paralelize the clone of repositories.
