### ISSUE TITLE
Create release notes process

### ISSUE THREAD

**Issue by maurorodrigues** [open-power-host-os/builds#43]
Let's use github.io pages to publish it.
Such page would be used to publish externally build's release notes (maybe a table of functionalities) and tests results/status.

cc/ @sathnaga @rquander FYI

**Comment by rmatinata-ibm** [comment]
Release Notes should contain:
 - Changelog
 - SHA1s
 - Features added
 - Known Issues
 - Closed Issues

**Comment by maurorodrigues** [comment]
Let's try a best effort to start having this at september, 14th

**Comment by mopsfelder** [comment]
The https://open-power-host-os.github.io/ is already in place.

Thank you all!
