### ISSUE TITLE
CI as a project deliverable

### ISSUE THREAD

**Issue by maurorodrigues** [open-power-host-os/builds#45]
Would be nice to delivery build and test infrastructure packaged somehow. 

Brainstorm: 
- ansible + container 
  Ansible would take care of starting such infrastructure and auto upgradability of the containerized components. Components, in a first glance: jenkins and jjb services for build and test (against a machine in the cluster), repository hosting packages built.

**Comment by fabianorosas** [comment]
We've made some progress towards this with ansible scripts to reproduce our jenkins setup. See the [infrastructure](https://github.com/open-power-host-os/infrastructure) repo.

Keep in mind that to achieve the goal of having a deliverable, there is still some work to do. At this point there's no containerization or packaging of any form.

**Comment by alanoe** [comment]
@rmatinata @maurorodrigues 

What is the benefit of providing our "CI" (it is just a Jenkins server which builds packages) to the community? Package building can be done via command line. The only one I see is providing a GUI to the build system.

**Comment by mopsfelder** [comment]
The repository open-power-host-os/infrastructure has everything needed to setup Jenkins and its jobs. We will likely not deliver any binary to the wild.
