### ISSUE TITLE
Trigger CI builds per commit on *every* project under open-power-host-os

### ISSUE THREAD

**Issue by maurorodrigues** [open-power-host-os/builds#47]
Currently builds are only triggered for open-power-host-os/versions and open-power-host-os/builds.

**Comment by fabianorosas** [comment]
With open-power-host-os/infrastructure/pull/15 we now have nightly builds which build HostOS packages and ISO.

**Comment by mopsfelder** [comment]
As discussed with the team today, we will not run or build HostOS on every commit of the components.
