### ISSUE TITLE
Create tags automatically for every submisssion (experimental) and weekly (stable candidates) builds

### ISSUE THREAD

**Issue by maurorodrigues** [open-power-host-os/builds#48]
To Be discussed.

**Comment by rmatinata-ibm** [comment]
Might involve breaking it down into multiple jobs, as well as creating a BVT sequence (i.e. does the build at least boots ??)

**Comment by mopsfelder** [comment]
Today we have weekly tags in both builds and versions repositories.  This issue seems obsolete, closing.
