### ISSUE TITLE
Remove pkvm_3_1_1 dist tag from all packages

### ISSUE THREAD

**Issue by maurorodrigues** [open-power-host-os/builds#52]
A thing we must pay attention when doing this is assure it still upgrades fine, if it doesn't it's possible obsoletes tag may help

**Comment by olavphibm** [comment]
Fixed by open-power-host-os/versions#19

**Comment by maurorodrigues** [comment]
Reopened as mentioned in review https://github.com/open-power-host-os/versions/pull/19#pullrequestreview-2823193

**Comment by olavphibm** [comment]
@maurorodrigues I believe open-power-host-os/versions#47 fixed this, right?

**Comment by maurorodrigues** [comment]
@olavphibm yes! Thanks for bring this up! 
Closed by open-power-host-os/versions#47
