### ISSUE TITLE
Remove _unpackaged_files_terminate_build 0 from rpmmacro

### ISSUE THREAD

**Issue by maurorodrigues** [open-power-host-os/builds#56]
%_unpackaged_files_terminate_build 0

This tag allows build rpm successfully even when there are unpackaged files. Let's figure out what the unpackaged files are an decide what to do with them instead of using this

**Comment by mopsfelder** [comment]
I removed `_unpackaged_files_terminate_build` from macro files and pushed the change to https://github.com/mopsfelder/versions/commit/e77dcd8d774702c18427bb7c05e9c5a376e3f3e6.

Now, I need to build and see what breaks :-)
