### ISSUE TITLE
Add docs for Kernel Live patching functionality

### ISSUE THREAD

**Issue by maurorodrigues** [open-power-host-os/builds#7]
Since build 22/Beta the kernel at https://github.com/open-power-host-os/linux includes the code necessary to use kernel's live patching (you can read about it here: http://mpe.github.io/posts/2016/05/23/kernel-live-patching-for-ppc64le/) but unfortunatelly it depends on newer gcc than centOS 7.2 ships therefore we need to document a step by step of how to enable kernel live patching.

**Comment by mopsfelder** [comment]
Kernel live patching feature is available since open-power-host-os/versions/pull/26 was merged.

Closing.
