### ISSUE TITLE
Build dependency removal fails when mentioned twice

### ISSUE THREAD

**Issue by maurorodrigues** [open-power-host-os/builds#71]
Build dep clean up fails when it's a dep for two or more packages cause it's already removed in a previous clean up step for another package. Happened in open-power-host-os/versions#22.

**Comment by maurorodrigues** [comment]
in fact it the issue is probably when the system is loading package deps cause librtas was built twice, that should never happen.

**Comment by olavphibm** [comment]
The fact that the package was built twice did not make the script fail, but is indeed an issue.

**Comment by maurorodrigues** [comment]
yeah, what I meant is: the script fails cause it tries to remove the deps twice... but it's doing that caues it's also building twice, meaning it's not unique on the moment the packages to be built are prepared
