### ISSUE TITLE
Add switch to specify repositories_path value

### ISSUE THREAD

**Issue by mopsfelder** [open-power-host-os/builds#82]
The value of ``repositories_path`` is only set in ``config.yaml``.

This request is to add a new command line switch in ``host-os-build.py``, e.g. ``--repos-path``, to allow setting its value.

**Comment by snowcrshd** [comment]
I can work on this.

Would the command line argument have precedence over the configuration file?

**Comment by olavphibm** [comment]
@snowcrshd Yes, like mentioned here https://github.com/open-power-host-os/builds/pull/90/files

**Comment by snowcrshd** [comment]
@olavphibm  cool

**Comment by fabianorosas** [comment]
@snowcrshd's patch fixes this issue.
