### ISSUE TITLE
Respect log_file value set in config.yaml

### ISSUE THREAD

**Issue by mopsfelder** [open-power-host-os/builds#83]
The value of ``log_file`` that is set in ``config.yaml`` is always overwritten by a default value in ``lib/config.py``, so ``log_file`` value in ``config.yaml`` is not respected.

A desirable precedence should be (least precedence listed first):

- ``config.yaml``
- default value in ``lib/config.py`` if ``log_file`` does not exist in ``config.yaml``
- ``--log-file`` switch

**Comment by fabianorosas** [comment]
@mopsfelder I couldn't reproduce this:
```
user@farosas4:~/builds $ ls log
ls: cannot access log: No such file or directory
user@farosas4:~/builds $ python host-os-build.py --log-file /home/user/builds/log
Logs available at /home/user/builds/log
^C
user@farosas4:~/builds $ ls log
log
```
