### ISSUE TITLE
Create RPM capable of setting up essential HostOS repositories

### ISSUE THREAD

**Issue by olavphibm** [open-power-host-os/builds#84]
The RPM should be capable, on install or through a script, of making sure the following repositories are installed and enabled:
base (pre-configured on CentOS)
updates (pre-configured on CentOS)
extras (pre-configured on CentOS)
epel
hostos (for now, only internal)
openstack (http://ftp.unicamp.br/pub/ppc64el/centos/7_2/openstack/mitaka/)

**Comment by olavphibm** [comment]
Let's come up with ideas on how to make that possible and easy for the user

**Comment by fabianorosas** [comment]
That seems similar to what was proposed in issue #53

**Comment by olavphibm** [comment]
@fabianorosas You're right, I'll close that issue as duplicate.

**Comment by mopsfelder** [comment]
Closing in favor of issue #53.
