### ISSUE TITLE
Setup CI to run build scripts unit tests automatically

### ISSUE THREAD

**Issue by snowcrshd** [open-power-host-os/builds#93]
This way we ensure we don't break the functionality when we make changes to the scripts.

Maybe Travis-CI or CircleCI would be good enough for this.

**Comment by fabianorosas** [comment]
https://github.com/open-power-host-os/infrastructure/pull/37 takes care of this.

**Comment by mopsfelder** [comment]
https://github.com/open-power-host-os/infrastructure/pull/37 was merged.  Closing.
